name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # سيتم التحديث التلقائي كلما رفعت كود لهذا الفرع

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href "/Wael-MathAcademy/"

      - name: Upload production-ready build artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2